// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABOhB42WE6T6sxaD37JiZTzLeZT7v1oCw',
    appId: '1:991713192487:web:6800cfbd07203d30a3fc02',
    messagingSenderId: '991713192487',
    projectId: 'attend-pro-f777c',
    authDomain: 'attend-pro-f777c.firebaseapp.com',
    storageBucket: 'attend-pro-f777c.appspot.com',
    measurementId: 'G-4DPECQ9GJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtb25ipu-NasKUu-62bPjpDdmSs23_fc',
    appId: '1:991713192487:android:49dfd565d1c98d76a3fc02',
    messagingSenderId: '991713192487',
    projectId: 'attend-pro-f777c',
    storageBucket: 'attend-pro-f777c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASBfhueKn4xBO4xBMYBBGL9dsJOgODa9M',
    appId: '1:991713192487:ios:87a69fab013693fba3fc02',
    messagingSenderId: '991713192487',
    projectId: 'attend-pro-f777c',
    storageBucket: 'attend-pro-f777c.appspot.com',
    iosBundleId: 'com.example.attendPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASBfhueKn4xBO4xBMYBBGL9dsJOgODa9M',
    appId: '1:991713192487:ios:87a69fab013693fba3fc02',
    messagingSenderId: '991713192487',
    projectId: 'attend-pro-f777c',
    storageBucket: 'attend-pro-f777c.appspot.com',
    iosBundleId: 'com.example.attendPro',
  );
}
